config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"

  resource :registeration
  resource :session
  resource :password_reset
  resources :campaigns
  resources :user

  resources :candidates do
    collection do
      get "recent"
      get "hot"
      get "pipeline"
      get "champions"
      get "joinings"
      get "icebox"
      get "archive"
      get "incomplete"
      get "alumni"
      get "employees"
      get "contractors"
      get "leads"
      get "nurture"
      get "inbound"
      post "leads", to: "candidates#settle_leads"
      post "inbound", to: "candidates#settle_inbound"
    end

    scope module: "candidate" do
      resources :interviews
      resources :checklists
      resources :notes
      resources :emails
      resources :reviews
      resources :campaigns
      resources :resume
      get "timeline", to: "timeline#index"
      patch "/update/bucket", to: "candidate#update_bucket", as: "update_bucket"
      patch "/update/status", to: "candidate#update_status", as: "update_status"
      patch "/update/campaign", to: "candidate#update_campaign", as: "update_campaign"
      patch "/update/owner", to: "candidate#update_owner", as: "update_owner"
      patch "/update/joining", to: "candidate#update_joining", as: "update_joining"
      patch "/update/recycle", to: "candidate#update_recycle", as: "update_recycle"
      patch "/toggle/recycle", to: "candidate#toggle_recycle", as: "toggle_recycle"
      patch "/reject_and_icebox", to: "candidate#reject_and_icebox", as: "reject_and_icebox"
      patch "/reject_and_archive", to: "candidate#reject_and_archive", as: "reject_and_archive"

      patch "/reward_to_recruiter/:recruiter_id", to: "candidate#reward_to_recruiter", as: "reward_to_recruiter"
      get "/edit/joining", to: "candidate#edit_joining", as: "edit_joining"
      get "/edit/recycle", to: "candidate#edit_recycle", as: "edit_recycle"
    end
  end

  resources :members do
    scope module: "member" do
      resources :interviews
      resources :reviews
      resources :feedbacks
      resources :candidates
      resources :reports
      get "timeline", to: "timeline#index"
    end
  end

  resources :openings do
    member do
      post :toggle_interviewer
    end
    collection do
      get "description"
    end

    scope module: "opening" do
      resources :interviews
      resources :associations
      resources :champions
      resources :note
      resources :description
      get "timeline", to: "timeline#index"
    end
  end

  namespace :account do
    resources :roles, except: [:new, :show]
    resources :sources, except: [:new, :show]
  end

  scope "/settings" do
    get "/profile", to: "user#profile", as: "profile"
    get "/password", to: "user#password", as: "setting_password"
    get "/import", to: "user#import", as: "import"
    post "/import_csv", to: "user#import_csv", as: "import_csv"
    patch "/password", to: "user#update_password", as: "edit_password"
    get "/preferences", to: "user#preferences", as: "user_preferences"
    patch "/avatar", to: "user#update_avatar", as: "avatar"
    delete "/avatar", to: "user#destroy_avatar", as: "destroy_avatar"
  end

  scope "/search" do
    get "/candidates", to: "search#candidates"
  end

  resources :interviews
  resources :reports
  resources :buckets
  resources :pipeline
  resources :checklists
  resources :campaigns
  post "/campaigns/:id/close", to: "campaigns#close", as: "close_campaign"

  get :events, controller: :dashboard
  get :recycles, controller: :dashboard
  get :recycle, controller: :recycles, action: :index
  post :recycle, controller: :recycles, action: :settle

  scope "report" do
    get "/candidates", to: "report/candidates#index", as: "report_candidates"
    get "/new_candidates", to: "report/new_candidates#index", as: "report_new_candidates"
    get "/update_candidates", to: "report/update_candidates#index", as: "report_update_candidates"
    get "/bucket_report", to: "report/bucket_report#index", as: "bucket_report"
  end

  scope "/public" do
    get "/thanks", to: "public/apply#thanks", as: "public_thanks"
    get "/team", to: "public/team#index", as: "public_team"
    get "/openings", to: "public/openings#index", as: "public_openings"
    get "/openings/apply", to: "public/apply#index", as: "public_apply"
    post "/openings/apply", to: "public/apply#create", as: "public_apply_create"
    get "/openings/:id", to: "public/openings#show", as: "show_public_openings"
  end
end

app/views/shared/_account_menu.html.erb
<aside class="px-2 py-6 sm:px-6 lg:py-0 lg:px-0 lg:col-span-3">
  <nav class="space-y-1" id="menu">
    <a href="<%= account_roles_path %>" class="<%= current_page?(account_roles_path) ? "selected" : "unselected" %>">
      <!-- Heroicon name: outline/user-circle -->
      <svg
        class="svg-icon"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        aria-hidden="true"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"
        />
      </svg>
      <span class="truncate">Roles</span>
    </a>
    <a href="<%= account_sources_path %>" class="<%= current_page?(account_sources_path) ? "selected" : "unselected" %>">
      <!-- Heroicon name: outline/user-circle -->
      <svg
        class="svg-icon"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        aria-hidden="true"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"
        />
      </svg>
      <span class="truncate">Sources</span>
    </a>
  </nav>
</aside>

app/views/shared/_error_messages.html.erb
<% if resource&.errors&.any? %>
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="p-4 rounded-xs bg-red-50" id="error_explanation">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: solid/x-circle -->
        <svg class="w-5 h-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <h3 class="text-sm font-medium text-red-800">
          <%= I18n.t("errors.messages.not_saved",
                     count: resource.errors.count,
                     resource: resource.class.model_name.human.downcase) %>
        </h3>
        <div class="mt-2 text-sm text-red-700">
          <ul class="pl-5 space-y-1 list-disc">
            <% resource.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_form_header.html.erb
  
<div >
  <h1 class="text-lg font-semibold dark:text-white">
    <%= title %>
  </h1>
  <p class="text-gray-500 dark:text-gray-400 text-sm">
    <%= subtitle %>
  </p>
</div>

app/views/shared/_form_messages.html.erb
<% if message %>
  <%= render "shared/success_message", message: message %>
<% end %>
<%= render "shared/error_messages", resource: resource %>

app/views/shared/_navbar.html.erb
<% if current_user.admin? or current_user.super_admin? %>
  <%= render "shared/navbar/admin" %>
<% elsif current_user.recruiter? %>
  <%= render "shared/navbar/recruiter" %>
<% elsif current_user.data? %>
  <%= render "shared/navbar/data" %>
<% elsif current_user.interviewer? %>
  <%= render "shared/navbar/interviewer" %>
<% elsif current_user.recruiter_admin? %>
  <%= render "shared/navbar/recruiter_admin" %>
<% else %>
  <%= render "shared/navbar/default" %>
<% end %>

app/views/shared/_no_result_found.html.erb
<div class="w-full text-center sm:rounded-sm">
  <div class="px-4 py-5 sm:p-6">
    <h3 class="text-md font-medium leading-6 text-center text-gray-900">
      No result found
    </h3>
    <div class="mt-2 text-sm text-center text-gray-500">
      <p>We have not found any result for current search query. Please modify filter criteria and search again.</p>
    </div>
  </div>
</div>

app/views/shared/_paginator.html.erb
<% link = pagy_anchor(pagy) %>

<nav aria-label="Pagination" class="inline-flex border border-gray-200 rounded-xs shadow-md pagy_nav pagination" role="navigation">
  <% if pagy.prev %>
    <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 page prev hover:text-gray-900 hover:bg-gray-100"><%== link.(pagy.prev, "&lt;", aria_label: "Previous") %></span>
  <% else %>
    <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 cursor-not-allowed page prev hover:bg-gray-100 disabled"><a role="link" aria-disabled="true" aria-label="Previous">&lt;</a></span>
  <% end %>
  <% pagy.series.each do |item| %>
    <% if item.is_a?(Integer) %>
      <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 page hover:text-gray-900 hover:bg-gray-100"><%== link.(item) %></span>
    <% elsif item.is_a?(String) %>
      <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 text-blue-600 bg-gray-100 border-r border-gray-200 page current hover:text-gray-900 hover:bg-gray-100"><%= item %></span>
    <% elsif item == :gap %>
      <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 page gap hover:bg-gray-100"><%== "&hellip;" %></span>
    <% end %>
  <% end %>
  <% if pagy.next %>
    <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 text-gray-900 border-r border-transparent border-gray-200 page hover:text-gray-900 next hover:bg-gray-100"><a      href="<%== pagy_url_for(pagy, pagy.next) %>"      rel="next"      aria-disabled="true"      aria-label="Next"    >&gt;    </a></span>
  <% else %>
    <span class="px-3 py-2 text-sm font-medium leading-tight text-gray-700 border-r border-gray-200 cursor-not-allowed page next disabled hover:bg-gray-100"><a role="link" aria-disabled="true" aria-label="Next">&gt;</a></span>
  <% end %>
</nav>

app/views/shared/_settings_menu.html.erb
<aside class="px-2 py-6 sm:px-6 lg:py-0 lg:px-0 lg:col-span-3">
  <nav class="space-y-1">
    <a href="<%= profile_path %>" class="<%= current_page?(profile_path) ? "selected" : "unselected" %>">
      <!-- Heroicon name: outline/user-circle -->
      <svg
        class="svg-icon"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        aria-hidden="true"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"
        />
      </svg>
      <span class="truncate">Profile</span>
    </a>
    <a href="<%= setting_password_path %>" class="<%= current_page?(setting_password_path) ? "selected" : "unselected" %>">
      <!-- Heroicon name: outline/key -->
      <svg
        class="svg-icon"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        aria-hidden="true"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z"
        />
      </svg>
      <span class="truncate">Password</span>
    </a>
    <a href="<%= user_preferences_path %>" class="<%= current_page?(user_preferences_path) ? "selected" : "unselected" %>">
      <svg
        class="svg-icon"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"
        />
      </svg>
      Preferences
    </a>
  </nav>
</aside>

app/views/shared/_success_message.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<% if !message.blank? %>
  <div class="p-4 rounded-xs bg-green-50" x-data="{open: true}" x-show="open" x-init="setTimeout(function(){open = false; }, 2000);">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: solid/check-circle -->
        <svg class="w-5 h-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <p class="text-sm font-medium text-green-800">
          <%= message %>
        </p>
      </div>
      <div class="hidden pl-3 ml-auto">
        <div class="-mx-1.5 -my-1.5">
          <button class="inline-flex bg-green-50 rounded-xs p-1.5 text-green-500 hover:bg-green-100 focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-offset-green-50 focus:ring-green-600">
            <span class="sr-only">Dismiss</span>
            <!-- Heroicon name: solid/x -->
            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>