config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"

  resource :registeration
  resource :session
  resource :password_reset
  resources :campaigns
  resources :user

  resources :candidates do
    collection do
      get "recent"
      get "hot"
      get "pipeline"
      get "champions"
      get "joinings"
      get "icebox"
      get "archive"
      get "incomplete"
      get "alumni"
      get "employees"
      get "contractors"
      get "leads"
      get "nurture"
      get "inbound"
      post "leads", to: "candidates#settle_leads"
      post "inbound", to: "candidates#settle_inbound"
    end

    scope module: "candidate" do
      resources :interviews
      resources :checklists
      resources :notes
      resources :emails
      resources :reviews
      resources :campaigns
      resources :resume
      get "timeline", to: "timeline#index"
      patch "/update/bucket", to: "candidate#update_bucket", as: "update_bucket"
      patch "/update/status", to: "candidate#update_status", as: "update_status"
      patch "/update/campaign", to: "candidate#update_campaign", as: "update_campaign"
      patch "/update/owner", to: "candidate#update_owner", as: "update_owner"
      patch "/update/joining", to: "candidate#update_joining", as: "update_joining"
      patch "/update/recycle", to: "candidate#update_recycle", as: "update_recycle"
      patch "/toggle/recycle", to: "candidate#toggle_recycle", as: "toggle_recycle"
      patch "/reject_and_icebox", to: "candidate#reject_and_icebox", as: "reject_and_icebox"
      patch "/reject_and_archive", to: "candidate#reject_and_archive", as: "reject_and_archive"

      patch "/reward_to_recruiter/:recruiter_id", to: "candidate#reward_to_recruiter", as: "reward_to_recruiter"
      get "/edit/joining", to: "candidate#edit_joining", as: "edit_joining"
      get "/edit/recycle", to: "candidate#edit_recycle", as: "edit_recycle"
    end
  end

  resources :members do
    scope module: "member" do
      resources :interviews
      resources :reviews
      resources :feedbacks
      resources :candidates
      resources :reports
      get "timeline", to: "timeline#index"
    end
  end

  resources :openings do
    member do
      post :toggle_interviewer
    end
    collection do
      get "description"
    end

    scope module: "opening" do
      resources :interviews
      resources :associations
      resources :champions
      resources :note
      resources :description
      get "timeline", to: "timeline#index"
    end
  end

  namespace :account do
    resources :roles, except: [:new, :show]
    resources :sources, except: [:new, :show]
  end

  scope "/settings" do
    get "/profile", to: "user#profile", as: "profile"
    get "/password", to: "user#password", as: "setting_password"
    get "/import", to: "user#import", as: "import"
    post "/import_csv", to: "user#import_csv", as: "import_csv"
    patch "/password", to: "user#update_password", as: "edit_password"
    get "/preferences", to: "user#preferences", as: "user_preferences"
    patch "/avatar", to: "user#update_avatar", as: "avatar"
    delete "/avatar", to: "user#destroy_avatar", as: "destroy_avatar"
  end

  scope "/search" do
    get "/candidates", to: "search#candidates"
  end

  resources :interviews
  resources :reports
  resources :buckets
  resources :pipeline
  resources :checklists
  resources :campaigns
  post "/campaigns/:id/close", to: "campaigns#close", as: "close_campaign"

  get :events, controller: :dashboard
  get :recycles, controller: :dashboard
  get :recycle, controller: :recycles, action: :index
  post :recycle, controller: :recycles, action: :settle

  scope "report" do
    get "/candidates", to: "report/candidates#index", as: "report_candidates"
    get "/new_candidates", to: "report/new_candidates#index", as: "report_new_candidates"
    get "/update_candidates", to: "report/update_candidates#index", as: "report_update_candidates"
    get "/bucket_report", to: "report/bucket_report#index", as: "bucket_report"
  end

  scope "/public" do
    get "/thanks", to: "public/apply#thanks", as: "public_thanks"
    get "/team", to: "public/team#index", as: "public_team"
    get "/openings", to: "public/openings#index", as: "public_openings"
    get "/openings/apply", to: "public/apply#index", as: "public_apply"
    post "/openings/apply", to: "public/apply#create", as: "public_apply_create"
    get "/openings/:id", to: "public/openings#show", as: "show_public_openings"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  normalizes :email, with: ->(email) { email.strip.downcase }

  generates_token_for :password_reset, expires_in: 15.minutes do
    password_salt&.last(10)
  end

  has_one_attached :avatar

  enum :role, data: 0, recruiter: 1, interviewer: 2, admin: 3, recruiter_admin: 4, super_admin: 5

  validate :avatar_content_type
  validate :avatar_size

  scope :recruiters, -> { where(role: [:recruiter, :recruiter_admin], active: true).order(:first_name) }
  scope :admins, -> { where(role: :admin, active: true) }
  scope :data, -> { where(role: :data, active: true) }
  scope :owners, -> { where(role: [:admin, :recruiter, :recruiter_admin], active: true).order(:first_name) }
  scope :interviewers, -> { where(role: [:interviewer, :admin], active: true).order(:first_name) }

  def avatar_size
    if avatar.attached? && avatar.blob.byte_size > 1.megabytes
      errors.add(:avatar, "size should not be more than 1MB")
    end
  end

  def name
    first_name + " " + last_name
  end

  def admin_or_recruiter_admin?
    admin? or recruiter_admin? or super_admin?
  end

  def avatar_content_type
    if avatar.attached? && !avatar.content_type.in?(%w(image/jpeg image/png))
      errors.add(:avatar, "must be a JPEG or PNG")
    end
  end

  def self.bot
    find_by(email: "bot@crownstack.com")
  end

  def self.aashish
    find_by(email: "aashishdhawan@crownstack.com")
  end

  def openings
    Opening.where(owner: self, active: true)
  end
end

app/controllers/user_controller.rb
class UserController < BaseController
  include ActiveStorage::SetCurrent
  before_action :set_user
  before_action :build_form, only: [:update_password, :password]

  def update
    #authorize @user

    respond_to do |format|
      if @user.update(user_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@user, partial: "user/forms/profile", locals: { message: "User was updated successfully", user: @user }) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@user, partial: "user/forms/profile", locals: { user: @user }) }
      end
    end
  end

  def update_password
    #authorize @user
    respond_to do |format|
      if @form.submit(change_password_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@user, partial: "user/forms/password", locals: { message: "Password was updated successfully", user: @user }) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@user, partial: "user/forms/password", locals: { user: @user }) }
      end
    end
  end

  def update_avatar
    #authorize @user
    respond_to do |format|
      if @user.avatar.attach(params[:user][:avatar])
        format.html { redirect_to profile_path, notice: "Avatar was updated successfully" }
      else
        format.html { redirect_to profile_path, alert: @user.errors.full_messages.join(" and ") }
      end
    end
  end

  def destroy_avatar
    #authorize @user
    respond_to do |format|
      if @user.avatar.destroy
        format.html { redirect_to profile_path, notice: "Avatar was deleted successfully" }
      else
        format.html { redirect_to profile_path, alert: "Avatar was not deleted" }
      end
    end
  end

  def import
  end

  def import_csv
    return redirect_to request.referer, notice: "No file added" if params[:file].nil?
    return redirect_to request.referer, notice: "Only CSV files allowed" unless params[:file].content_type == "text/csv"

    file = params[:file]
    bucket = params[:import][:bucket]
    opening_id = params[:import][:opening_id].to_i
    style = params[:import][:style]

    style.constantize.new.call(params[:file], bucket, opening_id)

    redirect_to request.referer, notice: "Operation Completed"
  end

  def preferences
    #authorize @user
  end

  def profile
    #authorize @user
  end

  def password
    #authorize @user
  end

  private

  def set_user
    @user ||= current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :role_id, :manager_id, :job_id, :discipline_id, :avatar, :phone)
  end

  def change_password_params
    params.require(:user).permit(:original_password, :new_password, :new_password_confirmation)
  end

  def build_form
    @form ||= ChangePasswordForm.new(@user)
  end
end

app/views/user/import.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-8">
    <%= form_tag import_csv_path, method: :post, multipart: true do %>
      <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
        <div class="sm:col-span-2">
          <div class="py-4">
            <h2 class="text-lg mb-1 font-semibold leading-none text-gray-900 dark:text-white">
              Import CSV File
            </h2>
            <label class="block mb-2 text-sm text-gray-500 dark:text-white" for="file_input">Please upload CSV files only. Other file types will result in automatic rejection by our ATS. File should be less than 5 MB.</label>

            <div class="items-center w-full sm:flex">
              <div class="w-full"><%= file_field_tag :file, accept: ".csv" %></div>
            </div>
          </div>

          <div>
            <label for="user-role" class="inline-flex items-center mb-2 text-sm font-medium text-gray-900 dark:text-white">
              Select which bucket to assign candidates to
              <button
                type="button"
                data-tooltip-target="tooltip-user-bucket"
                data-tooltip-style="dark"
                class="ml-1"
              >
                <svg
                  aria-hidden="true"
                  class="
                    w-4 h-4 text-gray-400 hover:text-gray-900
                    dark:hover:text-white dark:text-gray-500
                  "
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Show information</span>
              </button>
              <div
                id="tooltip-user-bucket"
                role="tooltip"
                class="
                  inline-block absolute invisible z-10 py-1 px-2 max-w-sm
                  text-xs font-normal text-white bg-gray-900 rounded-xs
                  shadow-xs opacity-0 tooltip dark:bg-gray-700
                "
              >
                In which bucket you want to these candidates after import.
                <div class="tooltip-arrow" data-popper-arrow></div>
              </div>
            </label>
            <%= select_tag :bucket, options_for_select(Candidate.buckets.map { |k, v| [k.humanize.capitalize, k] }), class: "form-text-field", :name => "import[bucket]" %>
          </div>

          <div class="sm:col-span-2 mt-4 mb-4">
            <label for="user-role" class="inline-flex items-center mb-2 text-sm font-medium text-gray-900 dark:text-white">
              Associate candidates with Job Opening
              <button
                type="button"
                data-tooltip-target="tooltip-user-opening"
                data-tooltip-style="dark"
                class="ml-1"
              >
                <svg
                  aria-hidden="true"
                  class="
                    w-4 h-4 text-gray-400 hover:text-gray-900
                    dark:hover:text-white dark:text-gray-500
                  "
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Show information</span>
              </button>
              <div
                id="tooltip-user-opening"
                role="tooltip"
                class="
                  inline-block absolute invisible z-10 py-1 px-2 max-w-sm
                  text-xs font-normal text-white bg-gray-900 rounded-xs
                  shadow-xs opacity-0 tooltip dark:bg-gray-700
                "
              >
                With which job opening you would like to Associate these candidates.
                <div class="tooltip-arrow" data-popper-arrow></div>
              </div>
            </label>
            <%= select_tag :opening_id, options_for_select(Opening.all.order(:title).map { |k, v| [k.title, k.id] }), class: "form-text-field", :name => "import[opening_id]" %>
          </div>

          <div class="sm:col-span-2 mt-4 mb-4">
            <label for="user-role" class="inline-flex items-center mb-2 text-sm font-medium text-gray-900 dark:text-white">
              Select type of import
              <button
                type="button"
                data-tooltip-target="tooltip-import-nature"
                data-tooltip-style="dark"
                class="ml-1"
              >
                <svg
                  aria-hidden="true"
                  class="
                    w-4 h-4 text-gray-400 hover:text-gray-900
                    dark:hover:text-white dark:text-gray-500
                  "
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Show information</span>
              </button>
              <div
                id="tooltip-import-nature"
                role="tooltip"
                class="
                  inline-block absolute invisible z-10 py-1 px-2 max-w-sm
                  text-xs font-normal text-white bg-gray-900 rounded-xs
                  shadow-xs opacity-0 tooltip dark:bg-gray-700
                "
              >
                Please select what type of data you are importing.
                <div class="tooltip-arrow" data-popper-arrow></div>
              </div>
            </label>
            <%= select_tag :opening_id, options_for_select([["Import Naukri Outbound Leads", "ImportNaukriOutboundLeads"], ["Import Naukri Inbound Leads", "ImportNaukriInboundLeads"]]), class: "form-text-field", :name => "import[style]" %>
          </div>

          <%= submit_tag "Import", class: "btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/user/notifications.html.erb
<main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
  <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
    <%= render "shared/settings_menu" %>
    <main class="max-w-xl pb-12 px-4 lg:col-span-6">
      <div>
        <div>
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            Notifications
          </h3>
          <p class="mt-1 text-sm text-gray-500">
            We'll always let you know about important changes, but you pick what else you want to hear about.
          </p>
        </div>
        <div class="mt-6">
          <fieldset>
            <legend class="text-base font-medium text-gray-900">
              By Email
            </legend>
            <div class="mt-4 space-y-4">
              <div class="relative flex items-start">
                <div class="flex items-center h-5">
                  <input id="comments" name="comments" type="checkbox" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded-sm">
                </div>
                <div class="ml-3 text-sm">
                  <label for="comments" class="font-medium text-gray-700">Comments</label>
                  <p class="text-gray-500">Get notified when someones posts a comment on a posting.</p>
                </div>
              </div>
              <div class="relative flex items-start">
                <div class="flex items-center h-5">
                  <input id="candidates" name="candidates" type="checkbox" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded-sm">
                </div>
                <div class="ml-3 text-sm">
                  <label for="candidates" class="font-medium text-gray-700">Candidates</label>
                  <p class="text-gray-500">Get notified when a candidate applies for a job.</p>
                </div>
              </div>
              <div class="relative flex items-start">
                <div class="flex items-center h-5">
                  <input id="offers" name="offers" type="checkbox" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded-sm">
                </div>
                <div class="ml-3 text-sm">
                  <label for="offers" class="font-medium text-gray-700">Offers</label>
                  <p class="text-gray-500">Get notified when a candidate accepts or rejects an offer.</p>
                </div>
              </div>
            </div>
          </fieldset>
          <fieldset class="mt-6">
            <div>
              <legend class="text-base font-medium text-gray-900">
                Push Notifications
              </legend>
              <p class="text-sm text-gray-500">These are delivered via SMS to your mobile phone.</p>
            </div>
            <div class="mt-4 space-y-4">
              <div class="flex items-center">
                <input id="push_everything" name="push_notifications" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                <label for="push_everything" class="ml-3 block text-sm font-medium text-gray-700">
                  Everything
                </label>
              </div>
              <div class="flex items-center">
                <input id="push_email" name="push_notifications" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                <label for="push_email" class="ml-3 block text-sm font-medium text-gray-700">
                  Same as email
                </label>
              </div>
              <div class="flex items-center">
                <input id="push_nothing" name="push_notifications" type="radio" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300">
                <label for="push_nothing" class="ml-3 block text-sm font-medium text-gray-700">
                  No push notifications
                </label>
              </div>
            </div>
          </fieldset>
        </div>
        <div class="mt-8 flex justify-end">
          <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent rounded-xs shadow-xs text-sm font-medium text-white bg-blue-500 hover:bg-blue-600 focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-light-blue-500">
            Save
          </button>
        </div>
      </div>
    </main>
  </div>
</main>

app/views/user/password.html.erb
<main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
  <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
    <%= render "shared/settings_menu" %>
    <main class="max-w-xl pb-12 px-4 lg:col-span-6">
      <%= turbo_frame_tag "password_form" do %>
        <%= render "user/forms/password", user: @user %>
      <% end %>
    </main>
  </div>
</main>

app/views/user/preferences.html.erb
<main class="pb-10 mx-auto max-w-7xl lg:py-12 lg:px-8">
  <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
    <%= render "shared/settings_menu" %>
    <main class="max-w-xl px-4 pb-12 lg:col-span-6">
      <%= render "shared/form_header", title: "Personal Preferences", subtitle: "Setup your personal preferences." %>
      <ul class="mt-2 divide-y divide-gray-200">
        <li class="flex items-center py-4">
          <%= check_box_tag "email_enabled", nil, true, data: { reflex: "click->EmployeeNotificationReflex#toggle_email_notification", id: @user.id }, class: "mr-5 w-4 h-4 text-indigo-600 border-gray-300 rounded-sm focus:ring-indigo-500" %>
          <div class="flex flex-col">
            <p class="block text-sm font-medium text-gray-900 dark:text-white" id="privacy-option-1-label">
              Enable email notifications
            </p>
            <p class="text-sm text-gray-500" id="privacy-option-1-description">
              Turning it off will disbale all email notifications meant for you.
            </p>
          </div>
        </li>
      </ul>
    </main>
  </div>
</main>

app/views/user/profile.html.erb
<main class="max-w-7xl mx-auto pb-10 lg:py-12 lg:px-8">
  <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
    <%= render "shared/settings_menu" %>
    <main class="max-w-xl pb-12 px-4 lg:col-span-6">
      <div class="mt-6 flex-grow lg:mt-0 lg:ml-6 lg:flex-shrink-0 lg:flex-grow-0">
        <%= turbo_frame_tag "profile_form" do %>
          <%= render "user/forms/profile", user: @user %>
        <% end %>
      </div>
    </main>

    <div class="flex"><%= render "user/forms/avatar", user: @user %></div>
  </div>
</main>