config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"

  resource :registeration
  resource :session
  resource :password_reset
  resources :campaigns
  resources :user

  resources :candidates do
    collection do
      get "recent"
      get "hot"
      get "pipeline"
      get "champions"
      get "joinings"
      get "icebox"
      get "archive"
      get "incomplete"
      get "alumni"
      get "employees"
      get "contractors"
      get "leads"
      get "nurture"
      get "inbound"
      post "leads", to: "candidates#settle_leads"
      post "inbound", to: "candidates#settle_inbound"
    end

    scope module: "candidate" do
      resources :interviews
      resources :checklists
      resources :notes
      resources :emails
      resources :reviews
      resources :campaigns
      resources :resume
      get "timeline", to: "timeline#index"
      patch "/update/bucket", to: "candidate#update_bucket", as: "update_bucket"
      patch "/update/status", to: "candidate#update_status", as: "update_status"
      patch "/update/campaign", to: "candidate#update_campaign", as: "update_campaign"
      patch "/update/owner", to: "candidate#update_owner", as: "update_owner"
      patch "/update/joining", to: "candidate#update_joining", as: "update_joining"
      patch "/update/recycle", to: "candidate#update_recycle", as: "update_recycle"
      patch "/toggle/recycle", to: "candidate#toggle_recycle", as: "toggle_recycle"
      patch "/reject_and_icebox", to: "candidate#reject_and_icebox", as: "reject_and_icebox"
      patch "/reject_and_archive", to: "candidate#reject_and_archive", as: "reject_and_archive"

      patch "/reward_to_recruiter/:recruiter_id", to: "candidate#reward_to_recruiter", as: "reward_to_recruiter"
      get "/edit/joining", to: "candidate#edit_joining", as: "edit_joining"
      get "/edit/recycle", to: "candidate#edit_recycle", as: "edit_recycle"
    end
  end

  resources :members do
    scope module: "member" do
      resources :interviews
      resources :reviews
      resources :feedbacks
      resources :candidates
      resources :reports
      get "timeline", to: "timeline#index"
    end
  end

  resources :openings do
    member do
      post :toggle_interviewer
    end
    collection do
      get "description"
    end

    scope module: "opening" do
      resources :interviews
      resources :associations
      resources :champions
      resources :note
      resources :description
      get "timeline", to: "timeline#index"
    end
  end

  namespace :account do
    resources :roles, except: [:new, :show]
    resources :sources, except: [:new, :show]
  end

  scope "/settings" do
    get "/profile", to: "user#profile", as: "profile"
    get "/password", to: "user#password", as: "setting_password"
    get "/import", to: "user#import", as: "import"
    post "/import_csv", to: "user#import_csv", as: "import_csv"
    patch "/password", to: "user#update_password", as: "edit_password"
    get "/preferences", to: "user#preferences", as: "user_preferences"
    patch "/avatar", to: "user#update_avatar", as: "avatar"
    delete "/avatar", to: "user#destroy_avatar", as: "destroy_avatar"
  end

  scope "/search" do
    get "/candidates", to: "search#candidates"
  end

  resources :interviews
  resources :reports
  resources :buckets
  resources :pipeline
  resources :checklists
  resources :campaigns
  post "/campaigns/:id/close", to: "campaigns#close", as: "close_campaign"

  get :events, controller: :dashboard
  get :recycles, controller: :dashboard
  get :recycle, controller: :recycles, action: :index
  post :recycle, controller: :recycles, action: :settle

  scope "report" do
    get "/candidates", to: "report/candidates#index", as: "report_candidates"
    get "/new_candidates", to: "report/new_candidates#index", as: "report_new_candidates"
    get "/update_candidates", to: "report/update_candidates#index", as: "report_update_candidates"
    get "/bucket_report", to: "report/bucket_report#index", as: "bucket_report"
  end

  scope "/public" do
    get "/thanks", to: "public/apply#thanks", as: "public_thanks"
    get "/team", to: "public/team#index", as: "public_team"
    get "/openings", to: "public/openings#index", as: "public_openings"
    get "/openings/apply", to: "public/apply#index", as: "public_apply"
    post "/openings/apply", to: "public/apply#create", as: "public_apply_create"
    get "/openings/:id", to: "public/openings#show", as: "show_public_openings"
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :submitter, class_name: "User", foreign_key: "submitter_id"
  has_rich_text :content

  enum :status, draft: 0, submitted: 1
  enum :nature, positive: 0, negative: 1, neutral: 2
end

app/controllers/member/reports_controller.rb
class Member::ReportsController < Member::BaseController
  before_action :set_report, only: %i[show edit update destroy]

  def index
    @reports = Report.where(user: @member).includes(:user, :submitter).order(created_at: :desc)
  end

  def new
    @report = Report.new
  end

  def create
    report = AddReport.call(@member, current_user, report_params, params[:commit]).result
    if report.persisted?
      redirect_to member_reports_path(@member), notice: "Report was created successfully"
    else
      redirect_to new_member_reports_path(@member), alert: "Report was not created. Please try again."
    end
  end

  def update
    @report.update(report_params)
    if params[:commit] == "submitted"
      @report.submitted!
    elsif params[:commit] == "draft"
      @report.draft!
    end
    redirect_to member_reports_path(@member), notice: "Report was updated successfully"
  end

  def edit
  end

  def show
  end

  def destroy
  end

  private

  def set_report
    @report ||= Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:title, :content, :nature, :status)
  end
end

app/controllers/report/base_controller.rb
class Report::BaseController < BaseController
end

app/controllers/report/bucket_report_controller.rb
class Report::BucketReportController < Report::BaseController

  def index
    entries = Candidate.bucket_report_query(candidates_filter_params)
    @bucket = params[:bucket]
    @stats = BucketReportStats.new(entries)

    @pagy, @candidates = pagy_nil_safe(params, entries, items: LIMIT)
    render_partial("report/update_candidates/candidate", collection: @candidates, cached: false)
  end

  private

  def candidates_filter_params
    params.except(:commit).permit(*BucketReportFilter::KEYS)
  end
end

app/controllers/report/candidates_controller.rb
class Report::CandidatesController < Report::BaseController
  def index
    entries = Candidate.query(candidates_filter_params)
    @stats = CandidatesStats.new(entries)

    @roles = Role.all
    @openings = Opening.all

    @pagy, @candidates = pagy_nil_safe(params, entries, items: LIMIT)
    render_partial("report/candidates/candidate", collection: @candidates, cached: false)
  end

  private

  def candidates_filter_params
    params.except(:commit).permit(*CandidatesFilter::KEYS)
  end
end

app/controllers/report/new_candidates_controller.rb
class Report::NewCandidatesController < Report::BaseController
  def index
    entries = Candidate.new_candidates_query(candidates_filter_params)
    @openings = Opening.active
    @stats = NewCandidatesStats.new(entries)

    @sources = Source.all

    @pagy, @candidates = pagy_nil_safe(params, entries, items: LIMIT)
    render_partial("report/new_candidates/candidate", collection: @candidates, cached: false)
  end

  private

  def candidates_filter_params
    params.except(:commit).permit(*NewCandidatesFilter::KEYS)
  end
end

app/controllers/report/update_candidates_controller.rb
class Report::UpdateCandidatesController < Report::BaseController
  def index
    entries = Candidate.update_candidates_query(candidates_filter_params)
    @stats = CandidatesStats.new(entries)

    @sources = Source.all

    @pagy, @candidates = pagy_nil_safe(params, entries, items: LIMIT)
    render_partial("report/update_candidates/candidate", collection: @candidates, cached: false)
  end

  private

  def candidates_filter_params
    params.except(:commit).permit(*UpdateCandidatesFilter::KEYS)
  end
end

app/controllers/reports_controller.rb
class ReportsController < BaseController
end

app/views/reports/index.html.erb
  <main class="pb-8">
  <div class="px-4 sm:px-6">
    <!-- Main 2 column grid -->
    <div class="grid items-start grid-cols-1 gap-2 pl-40 pr-40 lg:grid-cols-2 lg:gap-2">
      <!-- Left column -->
      <div class="grid grid-cols-1 gap-4 lg:col-span-1">
        <div class="max-w-2xl mx-auto mt-8 mb-8">
          <h3 class="px-3 text-xs font-bold tracking-wider text-gray-800 uppercase" id="candidate-reports">
            Candidates Reports
          </h3>
          <div class="mt-1 space-y-1" aria-labelledby="projects-headline">
            <a href="<%= report_candidates_path %>" class="flex items-center px-3 py-1 text-sm text-gray-600 rounded-sm group hover:text-gray-900 hover:bg-gray-50">
              <span class="truncate">
                Filter Candidates
              </span>
            </a>
            <a href="<%= report_new_candidates_path %>" class="flex items-center px-3 py-1 text-sm text-gray-600 rounded-sm group hover:text-gray-900 hover:bg-gray-50">
              <span class="truncate">
                New Candidates Report
              </span>
            </a>
            <a href="<%= report_update_candidates_path %>" class="flex items-center px-3 py-1 text-sm text-gray-600 rounded-sm group hover:text-gray-900 hover:bg-gray-50">
              <span class="truncate">
                Updated Candidates Report
              </span>
            </a>
            <a href="<%= report_new_candidates_path(created_after_date: Date.yesterday, created_before_date: Date.yesterday) %>" class="flex items-center px-3 py-1 text-sm text-gray-600 rounded-sm group hover:text-gray-900 hover:bg-gray-50">
              <span class="truncate">
                New Candidates Added Yesterday
              </span>
            </a>
            <a href="<%= report_new_candidates_path(created_after_date: Date.yesterday, created_before_date: Date.yesterday, source_id: 7) %>" class="flex items-center px-3 py-1 text-sm text-gray-600 rounded-sm group hover:text-gray-900 hover:bg-gray-50">
              <span class="truncate">
                New Leads Received Yesterday
              </span>
            </a>
            <a href="<%= report_update_candidates_path(updated_after_date: Date.yesterday, updated_before_date: Date.yesterday) %>" class="flex items-center px-3 py-1 text-sm text-gray-600 rounded-sm group hover:text-gray-900 hover:bg-gray-50">
              <span class="truncate">
                Updated Candidates Yesterday
              </span>
            </a>
          </div>
        </div>
      </div>
      <!-- Left column -->
      <div class="grid grid-cols-1 gap-4 lg:col-span-1">
        <div class="max-w-2xl mx-auto mt-8 mb-8">
        </div>
      </div>
    </div>
  </div>
</main>